/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAiInterviewRouteImport } from './routes/_authenticated/ai-interview'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInterviewRouteImport } from './routes/_authenticated/interview'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedCodingIndexRouteImport } from './routes/_authenticated/coding.index'
import { Route as AuthenticatedCodingSlugRouteImport } from './routes/_authenticated/coding.$slug'
import { Route as AuthenticatedVqrIndexRouteImport } from './routes/_authenticated/vqr.index'
import { Route as AuthenticatedVqrResultResultIdRouteImport } from './routes/_authenticated/vqr.result.$resultId'
import { Route as AuthenticatedVqrTestTestIdRouteImport } from './routes/_authenticated/vqr.test.$testId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiInterviewRoute =
  AuthenticatedAiInterviewRouteImport.update({
    id: '/ai-interview',
    path: '/ai-interview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewRoute = AuthenticatedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCodingIndexRoute =
  AuthenticatedCodingIndexRouteImport.update({
    id: '/coding/',
    path: '/coding/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCodingSlugRoute = AuthenticatedCodingSlugRouteImport.update({
  id: '/coding/$slug',
  path: '/coding/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVqrIndexRoute = AuthenticatedVqrIndexRouteImport.update({
  id: '/vqr/',
  path: '/vqr/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVqrResultResultIdRoute =
  AuthenticatedVqrResultResultIdRouteImport.update({
    id: '/vqr/result/$resultId',
    path: '/vqr/result/$resultId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVqrTestTestIdRoute =
  AuthenticatedVqrTestTestIdRouteImport.update({
    id: '/vqr/test/$testId',
    path: '/vqr/test/$testId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai-interview': typeof AuthenticatedAiInterviewRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/coding/$slug': typeof AuthenticatedCodingSlugRoute
  '/coding/': typeof AuthenticatedCodingIndexRoute
  '/vqr/': typeof AuthenticatedVqrIndexRoute
  '/vqr/result/$resultId': typeof AuthenticatedVqrResultResultIdRoute
  '/vqr/test/$testId': typeof AuthenticatedVqrTestTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai-interview': typeof AuthenticatedAiInterviewRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/coding/$slug': typeof AuthenticatedCodingSlugRoute
  '/coding': typeof AuthenticatedCodingIndexRoute
  '/vqr': typeof AuthenticatedVqrIndexRoute
  '/vqr/result/$resultId': typeof AuthenticatedVqrResultResultIdRoute
  '/vqr/test/$testId': typeof AuthenticatedVqrTestTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/ai-interview': typeof AuthenticatedAiInterviewRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/interview': typeof AuthenticatedInterviewRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/coding/$slug': typeof AuthenticatedCodingSlugRoute
  '/_authenticated/coding/': typeof AuthenticatedCodingIndexRoute
  '/_authenticated/vqr/': typeof AuthenticatedVqrIndexRoute
  '/_authenticated/vqr/result/$resultId': typeof AuthenticatedVqrResultResultIdRoute
  '/_authenticated/vqr/test/$testId': typeof AuthenticatedVqrTestTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/ai-interview'
    | '/dashboard'
    | '/interview'
    | '/profile'
    | '/coding/$slug'
    | '/coding/'
    | '/vqr/'
    | '/vqr/result/$resultId'
    | '/vqr/test/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/ai-interview'
    | '/dashboard'
    | '/interview'
    | '/profile'
    | '/coding/$slug'
    | '/coding'
    | '/vqr'
    | '/vqr/result/$resultId'
    | '/vqr/test/$testId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/ai-interview'
    | '/_authenticated/dashboard'
    | '/_authenticated/interview'
    | '/_authenticated/profile'
    | '/_authenticated/coding/$slug'
    | '/_authenticated/coding/'
    | '/_authenticated/vqr/'
    | '/_authenticated/vqr/result/$resultId'
    | '/_authenticated/vqr/test/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-interview': {
      id: '/_authenticated/ai-interview'
      path: '/ai-interview'
      fullPath: '/ai-interview'
      preLoaderRoute: typeof AuthenticatedAiInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview': {
      id: '/_authenticated/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthenticatedInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coding/': {
      id: '/_authenticated/coding/'
      path: '/coding'
      fullPath: '/coding/'
      preLoaderRoute: typeof AuthenticatedCodingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coding/$slug': {
      id: '/_authenticated/coding/$slug'
      path: '/coding/$slug'
      fullPath: '/coding/$slug'
      preLoaderRoute: typeof AuthenticatedCodingSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vqr/': {
      id: '/_authenticated/vqr/'
      path: '/vqr'
      fullPath: '/vqr/'
      preLoaderRoute: typeof AuthenticatedVqrIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vqr/result/$resultId': {
      id: '/_authenticated/vqr/result/$resultId'
      path: '/vqr/result/$resultId'
      fullPath: '/vqr/result/$resultId'
      preLoaderRoute: typeof AuthenticatedVqrResultResultIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vqr/test/$testId': {
      id: '/_authenticated/vqr/test/$testId'
      path: '/vqr/test/$testId'
      fullPath: '/vqr/test/$testId'
      preLoaderRoute: typeof AuthenticatedVqrTestTestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiInterviewRoute: typeof AuthenticatedAiInterviewRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInterviewRoute: typeof AuthenticatedInterviewRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedCodingSlugRoute: typeof AuthenticatedCodingSlugRoute
  AuthenticatedCodingIndexRoute: typeof AuthenticatedCodingIndexRoute
  AuthenticatedVqrIndexRoute: typeof AuthenticatedVqrIndexRoute
  AuthenticatedVqrResultResultIdRoute: typeof AuthenticatedVqrResultResultIdRoute
  AuthenticatedVqrTestTestIdRoute: typeof AuthenticatedVqrTestTestIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiInterviewRoute: AuthenticatedAiInterviewRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInterviewRoute: AuthenticatedInterviewRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedCodingSlugRoute: AuthenticatedCodingSlugRoute,
  AuthenticatedCodingIndexRoute: AuthenticatedCodingIndexRoute,
  AuthenticatedVqrIndexRoute: AuthenticatedVqrIndexRoute,
  AuthenticatedVqrResultResultIdRoute: AuthenticatedVqrResultResultIdRoute,
  AuthenticatedVqrTestTestIdRoute: AuthenticatedVqrTestTestIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
